export enum RouteNames {
  HOME = "HOME",
  BLOG_TATARSKAYA_FEDOTOVA_HOME ="BLOG_TATARSKAYA_FEDOTOVA_HOME",
  NEWS_BLOG_TATARSKAYA_FEDOTOVA = "NEWS_BLOG_TATARSKAYA_FEDOTOVA",
  CREATE_NEWS_BLOG_TATARSKAYA_FEDOTOVA = "CREATE_NEWS_BLOG_TATARSKAYA_FEDOTOVA"
}
